services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: prarthna005/website-uptime-monitoring:frontend
    ports:
      - "3000:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: prarthna005/website-uptime-monitoring:backend
    ports:
      - "5000:5000"

  ai-agent:
    build:
      context: ./ai-agent
      dockerfile: Dockerfile
    image: prarthna005/website-uptime-monitoring:ai-agent
    ports:
      - "6000:6000"

  db:
    image: mongo:6
    volumes:
      - ./website-uptime-monitoring:/data/db
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml